### ISSUE TITLE
double check IntervalRegressionCV predictions 

### ISSUE THREAD

**Issue by tdhock** [avinashbarnwal/aftXgboostPaper#2]
Hi @avinashbarnwal if you computed the predictions correctly using IntervalRegressionCV then they should be the same as the last column in these files, 
https://github.com/tdhock/neuroblastoma-data/blob/master/data/ATAC_JV_adipose/cv/equal_labels/testFolds/1/randomTrainOrderings/1/models/L1reg_linear_all/predictions.csv
- this is data set ATAC_JC_adipose
- cv type equal_labels
- test fold 1
- random train ordering 1 (should be same if you use 2-5 as well)

**Comment by tdhock** [comment]
predictions are on log scale. please make scatterplot (your pred vs this pred) to examine if your predictions are consistent.

**Comment by avinashbarnwal** [comment]
The last column is the predicted column. (using the full training set, excluding the given test fold)

**Comment by avinashbarnwal** [comment]
Hi Prof. Toby,

I am still not sure how https://github.com/tdhock/neuroblastoma-data/blob/master/demo-folds.R will lead to the creation of a test fold. I will explain my thinking here about the prediction file - 

https://github.com/tdhock/neuroblastoma-data/blob/master/data/ATAC_JV_adipose/cv/equal_labels/testFolds/1/randomTrainOrderings/1/models/L1reg_linear_all/predictions.csv

as you mentioned that in the https://github.com/avinashbarnwal/aftXgboostPaper/issues/2. 

Testfolds - https://github.com/tdhock/neuroblastoma-data/tree/master/data/ATAC_JV_adipose/cv/equal_labels/testFolds
First Fold when we keep 1 Test fold 
Test_Fold1-CrossValidation.png
<img width="1427" alt="Test_Fold1-CrossValidation" src="https://user-images.githubusercontent.com/6061417/68621947-f7fb3200-049e-11ea-8c4d-75fbf9dab4f6.png">


- https://github.com/tdhock/neuroblastoma-data/tree/master/data/ATAC_JV_adipose/cv/equal_labels/testFolds/1/randomTrainOrderings/1

Above are the training cross-validations not the test folds. Ideally, we should have a test fold differently compared to cross-validation folds.

**Comment by tdhock** [comment]
@avinashbarnwal I don't understand. Can you please repeat/rephrase your question?

**Comment by avinashbarnwal** [comment]
Prof. @tdhock, 

I am not able to locate the test fold for corresponding train folds. In the above pic, we only have corresponding validation fold created using training fold. Please let me know if it is still not clear.

**Comment by tdhock** [comment]
still not clear. can you repeat/rephrase in terms of a question?

the testFold/XXX path indicates the test fold ID = XXX

there are randomTrainOrderings/YYY directories but the YYY = random seed for ordering the training samples, which is irrelevant to your work.

Validation folds are not defined in those data files (you need to do that yourself in your code)

**Comment by avinashbarnwal** [comment]
Hi Prof. @tdhock ,

I hope i am clear this time. 
![test train](https://user-images.githubusercontent.com/6061417/68716564-82f92c80-0572-11ea-85ad-072f032afeb4.jpg)

the testFold/XXX path indicates the test fold ID = XXX. In this which file to choose because we have
testFold/XXX/randomTrainOrderings ?

**Comment by tdhock** [comment]
use randomTrainOrderings/YYY where YYY = anything (there should be no
difference as long as you are looking at the last column of the
predictions.csv files)

**Comment by avinashbarnwal** [comment]
Hi Prof. @tdhock,

I am able to fix the code. Now the results, we are getting is the same as the one you have created for predictions.

Results:-
Test Fold 1 - https://github.com/avinashbarnwal/aftXgboostPaper/blob/master/result/ATAC_JV_adipose/intervalCV/compare_benchmark_1.png
Test Fold 2 - https://github.com/avinashbarnwal/aftXgboostPaper/blob/master/result/ATAC_JV_adipose/intervalCV/compare_benchmark_2.png
Test Fold 3 - https://github.com/avinashbarnwal/aftXgboostPaper/blob/master/result/ATAC_JV_adipose/intervalCV/compare_benchmark_3.png
Test Fold 4 - https://github.com/avinashbarnwal/aftXgboostPaper/blob/master/result/ATAC_JV_adipose/intervalCV/compare_benchmark_4.png

**Comment by tdhock** [comment]
ok very good
